# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d30ca92821912858c3c70f8665ce9f0c"
application_url = "https://shiny-hornets-drum.loca.lt"
embedded = true
name = "pos-app"
handle = "pos-app-68"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_customers"

[auth]
redirect_urls = [
  "https://shiny-hornets-drum.loca.lt/auth/callback",
  "https://shiny-hornets-drum.loca.lt/auth/shopify/callback",
  "https://shiny-hornets-drum.loca.lt/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "https://shiny-hornets-drum.loca.lt"
subpath = "proxy"
prefix = "apps"

[build]
dev_store_url = "kleep-store.myshopify.com"
include_config_on_deploy = true
automatically_update_urls_on_dev = true
